[build]
base = "d2tactics/d2tactics-frontend"
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/opendota/*"
to = "https://d2tactics.onrender.com/opendota/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
